title:            Zack's Blog
description:      I'm a full stack app developer living in Sydney.
url:              http://blog.cmsight.com
signoff:          Zack Zhu
disqus_shortname: zackzhusblog
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-35816032-1

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /posts
  - name:         5coins
    url:          http://5coins.cmsight.com
    external:     true
  - name:         GitHub
    url:          http://github.com/codingrhythm
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
